all:
  children:
    cloud:
      hosts:
        arquivos:
          ansible_port: 2223
        backupcloud:
          ansible_port: 2225
        #bidu:
        #dnscloud:
        #  ansible_port: 2226
        #iris:
        #  ansible_port: 2224
        #moiras:
        #  ansible_port: 2223
        #mysql:
        #  ansible_port: 2225
        sambadc:
        testcloud:
          ansible_port: 2226
      children:
        nfs:
          hosts:
            moros:
              ansible_port: 2222
            mot:
              ansible_port: 2222
    container:
      hosts:
        #ansible:
        #athena:
        caneco:
        #clotho:
        #dnscache:
        #fradim:
        #labcead:
        #lollo:
        #meshcentral:
        #ocs:
        #sambabaca:
        #saori:
        #switchfw:
        #unifi:
        #www301:
        xicrinho:
        zoneminder:
    docker:
      hosts:
        porto:
          apps:
            - name: impressoras
              repo: https://github.com/wgnann/impressoras.git
    sambashare:
      hosts:
        scangrafica:
          share_name: scangrafica 
          share_user: scangrafica
    lab:
      hosts:
#        ete:
        gaspar:
        melchior:
        N045018035: # matheus-local.pc
        tigrinho: # laura-local
      children:
        bib:
          hosts:
            N045014625: #bibconsulta ex danielfa debian 12
            N045013725: #bib13 core2duo 1 andar
        blocob:
          hosts:
            N045016235: #Victor Olmos Prieto visitante ferenczi B159 17/9/2024
            allejo:
            cr7:
            dalton:
            messi:
            schala:
            slash:
        labets:
          hosts:
            serge:
            kid:
            lynx:
            guile:
            norris:
            nikki:
            viper:
            riddel:
            karsh:
            korcha:
            luccia:
            poshul:
            razzly:
            zappa:
            orcha:
            radius:
            glenn:
            leena:
            miki:
        labmae:
          hosts:
            aldebaran: #dualboot
            horologium: #dualboot
            hydra: #dualboot
            indus: #dualboot
            lacerta:
            lepus:
            libra:
            monoceros:
            norma:
            ophiucus:
            puppis:
            reticulum:
            sextans:
            sirius:
        labmap:
          hosts:
            maracaja: #ryzen 7 4600G num chieftec
        labcea:
          hosts:
            cea02:
            cea03:
            cea04: 
            cea05:
            cea06:
            cea08:
            cea09:
            cea12:
            cea14:
            cea15:
    dualboot:
      hosts:
    pve:
      hosts:
        #hermes:
        #netuno:
        #poseidon:
    ssh:
      hosts:
        hades:
        hades2:
        site:
      children:
        brucutuX:
          hosts:
            brucutu:
            brucutuIV:
            brucutuVI:
            brucutuVII:
    storage_server:
      hosts:
        storage:
    staff:
      hosts:
        compras4a3d-l:
        N045014864: #adailton compras i3 7100
        N045014867: #nasoares licitacao i3 6100
        svtes9b85-l:
        caema60a-wl:
        portaria-a:
        portaria-numec:
        N045018848:
        N045017320: # estagiario secmap
        N045019753: #secmac crism ryzen 3 3200g dualboot
        N045014721: #secmac chefia imac velho
        N045019369: # crint funcionária nova
        N045018588: #edinaarouca.pc
        N045019770: #estagiario ccsl
        N045014727: # estagiario ccex
        N045018590: #svmat renato.pavone i5-6400
        N045008745: #nova funcionaria licitacao i3-6100
    web:
      hosts:
        #cache:
        #  ansible_port: 2227
        #caos:
        #  ansible_port: 2225
        #cosmo:
        #  ansible_port: 2226
      children:
        svapin:
          hosts:
            #bibdigital:
            #  ansible_port: 2228
            #www:
            #  ansible_port: 2224
          vars:
            open_to: webadm
    windows:
      hosts:
        caem06c3-w:
        caem8cb0-wl:
        caemb358-wl:
        caemf13b-wl:
        cea01-w:
        cea02-w:
        cea03-w:
        cea04-w:
        cea05-w:
        cea06-w:
        cea07-w:
        cea08-w:
        cea09-w:
        cea10-w:
        cea11-w:
        cea12-w:
        cea13-w:
        cea14-w:
        cea15-w:
        caema60a-wl:
        caema60c-wl:
      children:
        win_classroom:
          hosts:
            congregacao: # dell i5 14700 16GB que fica na sala dos modems
            10.81.0.57: # dell i5 14700 16GB que fica na sala dos modems
            velikanova-w:
            dorothyvaughan: #maquina sala de aula que vão usar pra concurso na 136
        win_staff:
          hosts:
            secmae1607-w:
            secmae4be3-w:
            secmaefe04-w:
            secmap4bde-w:
            secmat13e8-w:
            secmat4abe-w:
            caema60a-wl:
            caema60c-wl:          
            N045018848:
            N200083503: # brigida
            N045014621:
            N045017282: #dell all-in-one i7 8GB w11 reserva na SI
            N045019019: #diretoria fabianac
            N045019741: #seccpg iro
            N045019744: #seccpg regiane
            N045019745: #seccpg rick
            N045019747: #ssg fransr cameras ryzen 3 3200g
            N045019753: #secmac crism ryzen 3 3200g dualboot
            N045019755: #seccpg luizinha
            N045019775: #seccpg apsv
            N045019788: #seccpg katiak
            N200116179: #atfin flavioteixeira ryzen 5 5600g
            N045014620: #bib yasuki itautreco velho
            N045014629: #bib ricardot itautreco velho encoding video
            N045015800: #svapin estagiarios era ip valido
            N045019018: #ataac sed daniscar
            N045019757: #matemateca patty ryzen 3 3200G
            N200069939: #svpes func novo dell AiO i5 10th Gen
            N200114915: #crint lenovo thinkpad gabrielamathias
            N045019786: #estagios ryzen 3 3200G claudiamarcelino
            N045019792: #audiovisual ryzen 7 3700x com plaquinha de video
        win_profs:
          hosts:

