- name: lab
  hosts: lab
  roles:
    - role: base
    - role: ssh
    - role: sssd-ad-uspdev
    - role: ui
    - role: dev
    - role: dev-x
    - role: texliveopt
    - role: lab
    - role: grub
      when: skip_grub is undefined
    - role: pam_mount
      when: skip_pam_mount is undefined
